// Code generated by protoc-gen-go. DO NOT EDIT.
// source: url.proto

package url // import "github.com/linqk/protobuft/net/url"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type URL struct {
	Scheme               string    `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Opaque               string    `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	User                 *UserInfo `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Host                 string    `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string    `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	RawPath              string    `protobuf:"bytes,6,opt,name=raw_path,json=rawPath,proto3" json:"raw_path,omitempty"`
	ForceQuery           bool      `protobuf:"varint,7,opt,name=force_query,json=forceQuery,proto3" json:"force_query,omitempty"`
	RawQuery             string    `protobuf:"bytes,8,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Fragment             string    `protobuf:"bytes,9,opt,name=fragment,proto3" json:"fragment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *URL) Reset()         { *m = URL{} }
func (m *URL) String() string { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()    {}
func (*URL) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_858312719d55786d, []int{0}
}
func (m *URL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URL.Unmarshal(m, b)
}
func (m *URL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URL.Marshal(b, m, deterministic)
}
func (dst *URL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URL.Merge(dst, src)
}
func (m *URL) XXX_Size() int {
	return xxx_messageInfo_URL.Size(m)
}
func (m *URL) XXX_DiscardUnknown() {
	xxx_messageInfo_URL.DiscardUnknown(m)
}

var xxx_messageInfo_URL proto.InternalMessageInfo

func (m *URL) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *URL) GetOpaque() string {
	if m != nil {
		return m.Opaque
	}
	return ""
}

func (m *URL) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *URL) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *URL) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *URL) GetRawPath() string {
	if m != nil {
		return m.RawPath
	}
	return ""
}

func (m *URL) GetForceQuery() bool {
	if m != nil {
		return m.ForceQuery
	}
	return false
}

func (m *URL) GetRawQuery() string {
	if m != nil {
		return m.RawQuery
	}
	return ""
}

func (m *URL) GetFragment() string {
	if m != nil {
		return m.Fragment
	}
	return ""
}

type UserInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordSet          bool     `protobuf:"varint,3,opt,name=password_set,json=passwordSet,proto3" json:"password_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_858312719d55786d, []int{1}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetPasswordSet() bool {
	if m != nil {
		return m.PasswordSet
	}
	return false
}

func init() {
	proto.RegisterType((*URL)(nil), "linqk.protobuft.URL")
	proto.RegisterType((*UserInfo)(nil), "linqk.protobuft.UserInfo")
}

func init() { proto.RegisterFile("url.proto", fileDescriptor_url_858312719d55786d) }

var fileDescriptor_url_858312719d55786d = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbf, 0x4e, 0xf3, 0x40,
	0x10, 0xc4, 0xe5, 0x24, 0x5f, 0x72, 0xde, 0x7c, 0x12, 0xd2, 0x15, 0xe8, 0x02, 0x05, 0xc1, 0xa2,
	0x70, 0x83, 0x2d, 0xc1, 0x1b, 0xd0, 0x21, 0x51, 0x80, 0x51, 0x1a, 0x1a, 0xeb, 0x6c, 0xd6, 0x71,
	0x84, 0xed, 0xb3, 0xef, 0x8f, 0x2c, 0x4a, 0xde, 0x1c, 0xdd, 0x5d, 0xec, 0x82, 0x6e, 0xe7, 0x37,
	0xbb, 0xa3, 0xd5, 0x40, 0x68, 0x64, 0x93, 0xf4, 0x52, 0x68, 0x41, 0x2f, 0x9a, 0x53, 0x37, 0x7c,
	0x79, 0x51, 0x98, 0x4a, 0x47, 0x3f, 0x0b, 0x58, 0x1e, 0xb2, 0x17, 0x7a, 0x09, 0x6b, 0x55, 0xd6,
	0xd8, 0x22, 0x0b, 0xf6, 0x41, 0x1c, 0x66, 0x67, 0x65, 0xb9, 0xe8, 0xf9, 0x60, 0x90, 0x2d, 0x3c,
	0xf7, 0x8a, 0xde, 0xc3, 0xca, 0x28, 0x94, 0x6c, 0xb9, 0x0f, 0xe2, 0xed, 0xc3, 0x2e, 0xf9, 0x93,
	0x9b, 0x1c, 0x14, 0xca, 0xe7, 0xae, 0x12, 0x99, 0x5b, 0xa3, 0x14, 0x56, 0xb5, 0x50, 0x9a, 0xad,
	0x5c, 0x88, 0x9b, 0x2d, 0xeb, 0xb9, 0xae, 0xd9, 0x3f, 0xcf, 0xec, 0x4c, 0x77, 0x40, 0x24, 0x1f,
	0x73, 0xc7, 0xd7, 0x8e, 0x6f, 0x24, 0x1f, 0x5f, 0xad, 0x75, 0x03, 0xdb, 0x4a, 0xc8, 0x12, 0xf3,
	0xc1, 0xa0, 0xfc, 0x66, 0x9b, 0x7d, 0x10, 0x93, 0x0c, 0x1c, 0x7a, 0xb3, 0x84, 0x5e, 0x43, 0x68,
	0x6f, 0xbd, 0x4d, 0xdc, 0xb1, 0x0d, 0xf3, 0xe6, 0x15, 0x90, 0x4a, 0xf2, 0x63, 0x8b, 0x9d, 0x66,
	0xa1, 0xf7, 0x26, 0x1d, 0x21, 0x90, 0xe9, 0x5d, 0xbb, 0x67, 0x1f, 0xee, 0xf8, 0xdc, 0xc4, 0xac,
	0xad, 0xd7, 0x73, 0xa5, 0x46, 0x21, 0x3f, 0xcf, 0x6d, 0xcc, 0x9a, 0xde, 0xc2, 0xff, 0x69, 0xce,
	0x15, 0x6a, 0xd7, 0x0b, 0xc9, 0xb6, 0x13, 0x7b, 0x47, 0xfd, 0x74, 0xf7, 0x11, 0x1d, 0x4f, 0xba,
	0x36, 0x45, 0x52, 0x8a, 0x36, 0x75, 0x85, 0xa5, 0x73, 0x61, 0x69, 0x87, 0x3a, 0x35, 0xb2, 0x29,
	0xd6, 0x0e, 0x3d, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x05, 0x00, 0x97, 0x4e, 0xb5, 0x01, 0x00,
	0x00,
}
